package com.example.collegeapp.home

import android.content.Context
import com.example.collegeapp.R

class RecyclerDataTemp {
    fun articleList(context: Context): List<ArticleEntity> {
        val resultList = mutableListOf<ArticleEntity>()
        resultList.add(
            ArticleEntity(
                context.getString(R.string.label_fake_title_post),
                R.drawable.background_image,
                context.getString(R.string.label_time_fake),
                context.getString(R.string.label_writer_fake),
                context.getString(R.string.label_tag_fake)
            )
        )
        resultList.add(
            ArticleEntity(
                context.getString(R.string.label_fake_title_post),
                R.drawable.background_image,
                context.getString(R.string.label_time_fake),
                context.getString(R.string.label_writer_fake),
                context.getString(R.string.label_tag_fake)
            )
        )
        resultList.add(
            ArticleEntity(
                context.getString(R.string.label_fake_title_post),
                R.drawable.background_image,
                context.getString(R.string.label_time_fake),
                context.getString(R.string.label_writer_fake),
                context.getString(R.string.label_tag_fake)
            )
        )
        resultList.add(
            ArticleEntity(
                context.getString(R.string.label_fake_title_post),
                R.drawable.background_image,
                context.getString(R.string.label_time_fake),
                context.getString(R.string.label_writer_fake),
                context.getString(R.string.label_tag_fake)
            )
        )
        resultList.add(
            ArticleEntity(
                context.getString(R.string.label_fake_title_post),
                R.drawable.background_image,
                context.getString(R.string.label_time_fake),
                context.getString(R.string.label_writer_fake),
                context.getString(R.string.label_tag_fake)
            )
        )
        resultList.add(
            ArticleEntity(
                context.getString(R.string.label_fake_title_post),
                R.drawable.background_image,
                context.getString(R.string.label_time_fake),
                context.getString(R.string.label_writer_fake),
                context.getString(R.string.label_tag_fake)
            )
        )
        resultList.add(
            ArticleEntity(
                context.getString(R.string.label_fake_title_post),
                R.drawable.background_image,
                context.getString(R.string.label_time_fake),
                context.getString(R.string.label_writer_fake),
                context.getString(R.string.label_tag_fake)
            )
        )
        resultList.add(
            ArticleEntity(
                context.getString(R.string.label_fake_title_post),
                R.drawable.background_image,
                context.getString(R.string.label_time_fake),
                context.getString(R.string.label_writer_fake),
                context.getString(R.string.label_tag_fake)
            )
        )
        resultList.add(
            ArticleEntity(
                context.getString(R.string.label_fake_title_post),
                R.drawable.background_image,
                context.getString(R.string.label_time_fake),
                context.getString(R.string.label_writer_fake),
                context.getString(R.string.label_tag_fake)
            )
        )
        resultList.add(
            ArticleEntity(
                context.getString(R.string.label_fake_title_post),
                R.drawable.background_image,
                context.getString(R.string.label_time_fake),
                context.getString(R.string.label_writer_fake),
                context.getString(R.string.label_tag_fake)
            )
        )
        resultList.add(
            ArticleEntity(
                context.getString(R.string.label_fake_title_post),
                R.drawable.background_image,
                context.getString(R.string.label_time_fake),
                context.getString(R.string.label_writer_fake),
                context.getString(R.string.label_tag_fake)
            )
        )
        return resultList.toList()
    }
}